version: '3.8'

services:
  db:
    image: postgres:15-alpine@sha256:987b242173006d6df08506f10b967a71478a3610664cfefbc49b9c775d3d0eed
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_USER: budget_user
      POSTGRES_DB: adhd_budget
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    mem_limit: 512m
    cpus: '0.5'
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - DAC_OVERRIDE

  mcp-server:
    image: python:3.11-alpine@sha256:8d8c6d3808243160605925c2a7ab2dc5c72d0e75651699b0639143613e0855b8
    user: "1000:1000"
    volumes:
      - ./src:/app
    working_dir: /app
    command: python /app/simple_mcp_server.py
    environment:
      - MCP_PORT=8081
      - MCP_AUTH_TOKEN=${MCP_TOKEN:-secret}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    mem_limit: 256m
    cpus: '0.25'
    cap_drop:
      - ALL
    depends_on:
      db:
        condition: service_healthy

  worker:
    image: python:3.11-alpine@sha256:8d8c6d3808243160605925c2a7ab2dc5c72d0e75651699b0639143613e0855b8
    user: "1000:1000"
    volumes:
      - ./src:/app
    working_dir: /app
    command: sh -c "echo 'Worker started' && sleep infinity"
    environment:
      - ENABLE_BANKING_KEY=${ENABLE_BANKING_KEY}
      - ENABLE_BANKING_SECRET=${ENABLE_BANKING_SECRET}
    restart: unless-stopped
    mem_limit: 256m
    cpus: '0.25'
    cap_drop:
      - ALL
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./src:/app
    environment:
      - API_PORT=8082
      - API_AUTH_TOKEN=${API_TOKEN:-api-secret}
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8082"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    mem_limit: 128m
    cpus: '0.25'
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile.caddy-secure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.test:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    mem_limit: 128m
    cpus: '0.25'
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    depends_on:
      - api
      - mcp-server
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine@sha256:bb186d083732f669da90be8b0f975a37812b15e913465bb14d845db72a4e3e08
    user: "999:999"  # Redis user
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    mem_limit: 128m
    cpus: '0.25'
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=adhd_budget
      - DB_USER=budget_user
      - DB_PASSWORD=changeme
      - API_URL=http://api:8082
      - MCP_URL=http://mcp-server:8081
      - PROXY_URL=http://reverse-proxy
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
      mcp-server:
        condition: service_started
      reverse-proxy:
        condition: service_started
    networks:
      - default
    profiles:
      - test

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  default:
    name: adhd_budget_network